version: '3.9'
services:
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    environment:
      - OLLAMA_HOST=http://0.0.0.0:11438
    network_mode: "host"
    container_name: ollama
    volumes:
      - ollama:/app
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    network_mode: "host"
    command: python3 app.py
    container_name: flask
    volumes:
      - flask:/app
    depends_on:
      - ollama
    command: python3 app.py

  react:
    build:    
      context: ./react
      dockerfile: Dockerfile
    network_mode: "host"

    volumes:
      - react:/app

    container_name: react
    depends_on:
      - flask
      - ollama
        
        
volumes:
  ollama:
  flask:
  react:
    
